export const sections = [
    { name: "ดินขุดดินถม", 
    funcName: "cutandfill", 
    heading: "", 
    subtitle: `
        
    ` },
    { name: "ทรายหยาบ", funcName: "coarsesand", heading: "", subtitle: "" },
    { name: "คอนกรีตหยาบ", funcName: "roughconcrete", heading: "", subtitle: "" },
    { name: "คอนกรีตโครงสร้าง", funcName: "structuralconcrete", heading: "", subtitle: "" },
    { name: "คอนกรีตเสาหลัก", funcName: "concretegroundColumn_main", heading: "", subtitle: "" },
    { name: "ปริมาณคอนกรีตเสาหลัก", funcName: "concretequantity_main", heading: "", subtitle: "" },
    { name: "ไม้แบบเสาหลัก", funcName: "Shutterboardscolunm_main", heading: "", subtitle: "" },
    { name: "คอนกรีตเสา", funcName: "concretegroundColumn", heading: "", subtitle: "" },
    { name: "ปริมาณคอนกรีต", funcName: "concretequantity", heading: "", subtitle: "" },
    { name: "ไม้แบบเสา", funcName: "Shutterboardscolunm", heading: "", subtitle: "" },
    { name: "คอนกรีตคาน", funcName: "concreatebeam", heading: "", subtitle: "" },
    { name: "ไม้แบบคาน", funcName: "Shutterboardsbeam", heading: "", subtitle: "" },
    { name: "พื้น S", funcName: "floor_S", heading: "", subtitle: "" },
    { name: "พื้น PS", funcName: "floor_PS", heading: "", subtitle: "" },
    { name: "หาความลาดเอียงหลังคา", funcName: "getAngleDeg", heading: "", subtitle: "" },
    { name: "หลังคาทรงปั้นหยา", funcName: "hipped_roof", heading: "", subtitle: "" },
    { name: "เหล็กปลอกฐานราก", funcName: "Stirrup_factor", heading: "", subtitle: "" },
    { name: "เหล็กฐานราก", funcName: "iron_factor", heading: "", subtitle: "" },
    { name: "เสาตอม่อ", funcName: "stanchion", heading: "", subtitle: "" },
    { name: "เหล็กปลอกเสาตอม่อ", funcName: "Stirrup_stanchion", heading: "", subtitle: "" },
    { name: "เหล็กเสาตอม่อหลัก", funcName: "iron_colunm", heading: "", subtitle: "" },
    { name: "เหล็กคาน", funcName: "iron_beam", heading: "", subtitle: "" },
    { name: "เหล็กปลอกคาน", funcName: "iron_beam_caszing", heading: "", subtitle: "" },
  ]
  